apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: lab2-tradr-config
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: lab2-tradr-config
    data:
      stockQuote.url: "stockquote.com"
      tradeHistory.url: "tradehistory.com"
      portfolio.url: "portfolio.com"
